eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka/
server:
    port: 8081
spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_b23
    username: root
    password: root
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

